# Generated by Django 3.2.9 on 2021-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('yr_mfr', models.IntegerField()),
                ('date_mfr', models.DateField()),
                ('fuel_type', models.CharField(max_length=30)),
                ('kms_run', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('times_viewed', models.IntegerField()),
                ('body_type', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('variant', models.CharField(max_length=100)),
                ('assured_buy', models.BooleanField(max_length=30)),
                ('emi_starts_from', models.IntegerField()),
                ('booking_down_pymnt', models.IntegerField()),
                ('total_owners', models.IntegerField()),
            ],
        ),
    ]
