# Generated by Django 3.2.9 on 2021-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='body_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='fuel_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transmission',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='variant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
